

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"#services:
    volumes:
      - .app:/app
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate  && python manage.py runserver 0.0.0.0:8000"


#  db:
#    image: postgres
#    container_name: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=cybrix
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
#
#  app:
#    build: .
#    image: app:django
#    container_name: django
#    command: sh -c "python manage.py makemigrations && python manage.py migrate  && python manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - .:/django
#    ports:
#      - "8000:8000"
#    restart: always
#    depends_on:
#      - db
