---
name: Checks

on: [ push, pull_request ]

#jobs:
#    build:
#        runs-on: ubuntu-latest
#        steps:
#            - uses: actions/checkout@v2
#            - uses: actions/setup-python@v2
#                with:
#                    python-version: "3.9"
#            - name: Install dependencies
#                run: |
#                    python -m pip install --upgrade pip
#                    pip install -r requirements.txt
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      -name: Lint
        run: docker-compose run --rm app sh -c "flake8"
